package ie.gmit.sw;

/**
 * Enumeration of all 235 languages contained in the Wikipedia Language Identification (WiLi) database.
 * <p>
 * The {@link java.lang.Character.UnicodeBlock} of each language is also represented, however it is not fully accurate.
 * For instance, most languages don't use "Basic Latin" but rather an extended character set which includes diacritics
 * and other special characters.
 */
public enum Language {
    Achinese("Achinese", Character.UnicodeBlock.BASIC_LATIN),
    Afrikaans("Afrikaans", Character.UnicodeBlock.BASIC_LATIN),
    Albanian("Albanian", Character.UnicodeBlock.BASIC_LATIN),
    AlemannicGerman("Alemannic German", Character.UnicodeBlock.BASIC_LATIN),
    Amharic("Amharic", Character.UnicodeBlock.ETHIOPIC),
    Arabic("Arabic", Character.UnicodeBlock.ARABIC),
    Aragonese("Aragonese", Character.UnicodeBlock.BASIC_LATIN),
    Armenian("Armenian", Character.UnicodeBlock.ARMENIAN),
    Aromanian("Aromanian", Character.UnicodeBlock.BASIC_LATIN),
    Arpitan("Arpitan", Character.UnicodeBlock.BASIC_LATIN),
    Assamese("Assamese", Character.UnicodeBlock.BENGALI),
    Asturian("Asturian", Character.UnicodeBlock.BASIC_LATIN),
    Avar("Avar", Character.UnicodeBlock.CYRILLIC),
    Aymara("Aymara", Character.UnicodeBlock.BASIC_LATIN),
    Azerbaijani("Azerbaijani", Character.UnicodeBlock.BASIC_LATIN),
    Banjar("Banjar", Character.UnicodeBlock.ARABIC),
    Banyumasan("Banyumasan", Character.UnicodeBlock.BASIC_LATIN),
    Bashkir("Bashkir", Character.UnicodeBlock.CYRILLIC),
    Basque("Basque", Character.UnicodeBlock.BASIC_LATIN),
    Bavarian("Bavarian", Character.UnicodeBlock.BASIC_LATIN),
    Belarusian("Belarusian", Character.UnicodeBlock.CYRILLIC),
    BelarusianTaraschkewiza("Belarusian Taraschkewiza", Character.UnicodeBlock.CYRILLIC),
    Bengali("Bengali", Character.UnicodeBlock.BENGALI),
    Bhojpuri("Bhojpuri", Character.UnicodeBlock.DEVANAGARI),
    Bishnupriya("Bishnupriya", Character.UnicodeBlock.BENGALI),
    Bokm("Bokm", Character.UnicodeBlock.BASIC_LATIN),
    Bosnian("Bosnian", Character.UnicodeBlock.BASIC_LATIN),
    Breton("Breton", Character.UnicodeBlock.BASIC_LATIN),
    Bulgarian("Bulgarian", Character.UnicodeBlock.CYRILLIC),
    Burmese("Burmese", Character.UnicodeBlock.MYANMAR),
    Buryat("Buryat", Character.UnicodeBlock.CYRILLIC),
    Cantonese("Cantonese", Character.UnicodeBlock.CJK_UNIFIED_IDEOGRAPHS),
    Catalan("Catalan", Character.UnicodeBlock.BASIC_LATIN),
    Cebuano("Cebuano", Character.UnicodeBlock.BASIC_LATIN),
    CentralBikol("Central Bikol", Character.UnicodeBlock.BASIC_LATIN),
    CentralKhmer("Central Khmer", Character.UnicodeBlock.KHMER),
    CentralKurdish("Central Kurdish", Character.UnicodeBlock.ARABIC),
    Chavacano("Chavacano", Character.UnicodeBlock.BASIC_LATIN),
    Chechen("Chechen", Character.UnicodeBlock.CYRILLIC),
    Cherokee("Cherokee", Character.UnicodeBlock.CHEROKEE),
    Chuvash("Chuvash", Character.UnicodeBlock.CYRILLIC),
    ClassicalNahuatl("Classical Nahuatl", Character.UnicodeBlock.BASIC_LATIN),
    Cornish("Cornish", Character.UnicodeBlock.BASIC_LATIN),
    Corsican("Corsican", Character.UnicodeBlock.BASIC_LATIN),
    CrimeanTatar("Crimean Tatar", Character.UnicodeBlock.BASIC_LATIN),
    Croatian("Croatian", Character.UnicodeBlock.BASIC_LATIN),
    Czech("Czech", Character.UnicodeBlock.BASIC_LATIN),
    Danish("Danish", Character.UnicodeBlock.BASIC_LATIN),
    Dhivehi("Dhivehi", Character.UnicodeBlock.THAANA),
    Dimli("Dimli", Character.UnicodeBlock.BASIC_LATIN),
    Doteli("Doteli", Character.UnicodeBlock.DEVANAGARI),
    Dutch("Dutch", Character.UnicodeBlock.BASIC_LATIN),
    EasternMari("Eastern Mari", Character.UnicodeBlock.CYRILLIC),
    EgyptianArabic("Egyptian Arabic", Character.UnicodeBlock.ARABIC),
    Emilian("Emilian", Character.UnicodeBlock.BASIC_LATIN),
    English("English", Character.UnicodeBlock.BASIC_LATIN),
    Erzya("Erzya", Character.UnicodeBlock.CYRILLIC),
    Esperanto("Esperanto", Character.UnicodeBlock.BASIC_LATIN),
    Estonian("Estonian", Character.UnicodeBlock.BASIC_LATIN),
    Extremaduran("Extremaduran", Character.UnicodeBlock.BASIC_LATIN),
    Faroese("Faroese", Character.UnicodeBlock.BASIC_LATIN),
    FijiHindi("Fiji Hindi", Character.UnicodeBlock.BASIC_LATIN),
    Finnish("Finnish", Character.UnicodeBlock.BASIC_LATIN),
    French("French", Character.UnicodeBlock.BASIC_LATIN),
    Friulian("Friulian", Character.UnicodeBlock.BASIC_LATIN),
    Gagauz("Gagauz", Character.UnicodeBlock.BASIC_LATIN),
    Galician("Galician", Character.UnicodeBlock.BASIC_LATIN),
    Georgian("Georgian", Character.UnicodeBlock.GEORGIAN),
    German("German", Character.UnicodeBlock.BASIC_LATIN),
    Gilaki("Gilaki", Character.UnicodeBlock.ARABIC),
    Guarani("Guarani", Character.UnicodeBlock.BASIC_LATIN),
    Gujarati("Gujarati", Character.UnicodeBlock.GUJARATI),
    HaitianCreole("Haitian Creole", Character.UnicodeBlock.BASIC_LATIN),
    HakkaChinese("Hakka Chinese", Character.UnicodeBlock.CJK_UNIFIED_IDEOGRAPHS),
    Hausa("Hausa", Character.UnicodeBlock.BASIC_LATIN),
    Hebrew("Hebrew", Character.UnicodeBlock.HEBREW),
    Hindi("Hindi", Character.UnicodeBlock.DEVANAGARI),
    Hungarian("Hungarian", Character.UnicodeBlock.BASIC_LATIN),
    Icelandic("Icelandic", Character.UnicodeBlock.BASIC_LATIN),
    Ido("Ido", Character.UnicodeBlock.BASIC_LATIN),
    Igbo("Igbo", Character.UnicodeBlock.BASIC_LATIN),
    Iloko("Iloko", Character.UnicodeBlock.BASIC_LATIN),
    Indonesian("Indonesian", Character.UnicodeBlock.BASIC_LATIN),
    Interlingua("Interlingua", Character.UnicodeBlock.BASIC_LATIN),
    Interlingue("Interlingue", Character.UnicodeBlock.BASIC_LATIN),
    Irish("Irish", Character.UnicodeBlock.BASIC_LATIN),
    Italian("Italian", Character.UnicodeBlock.BASIC_LATIN),
    JamaicanPatois("Jamaican Patois", Character.UnicodeBlock.BASIC_LATIN),
    Japanese("Japanese", Character.UnicodeBlock.KATAKANA, Character.UnicodeBlock.HIRAGANA, Character.UnicodeBlock.CJK_UNIFIED_IDEOGRAPHS),
    Javanese("Javanese", Character.UnicodeBlock.BASIC_LATIN),
    Kabardian("Kabardian", Character.UnicodeBlock.CYRILLIC),
    Kabyle("Kabyle", Character.UnicodeBlock.BASIC_LATIN),
    Kannada("Kannada", Character.UnicodeBlock.KANNADA),
    KarachayBalkar("Karachay Balkar", Character.UnicodeBlock.CYRILLIC),
    Karakalpak("Karakalpak", Character.UnicodeBlock.BASIC_LATIN),
    Kashubian("Kashubian", Character.UnicodeBlock.BASIC_LATIN),
    Kazakh("Kazakh", Character.UnicodeBlock.CYRILLIC),
    Kinyarwanda("Kinyarwanda", Character.UnicodeBlock.BASIC_LATIN),
    Kirghiz("Kirghiz", Character.UnicodeBlock.CYRILLIC),
    Komi("Komi", Character.UnicodeBlock.CYRILLIC),
    KomiPermyak("Komi Permyak", Character.UnicodeBlock.CYRILLIC),
    Konkani("Konkani", Character.UnicodeBlock.BASIC_LATIN, Character.UnicodeBlock.DEVANAGARI),
    Korean("Korean", Character.UnicodeBlock.CJK_UNIFIED_IDEOGRAPHS),
    Kurdish("Kurdish", Character.UnicodeBlock.BASIC_LATIN),
    Ladino("Ladino", Character.UnicodeBlock.BASIC_LATIN),
    Lao("Lao", Character.UnicodeBlock.LAO),
    Latgalian("Latgalian", Character.UnicodeBlock.BASIC_LATIN),
    Latin("Latin", Character.UnicodeBlock.BASIC_LATIN),
    Latvian("Latvian", Character.UnicodeBlock.BASIC_LATIN),
    Lezghian("Lezghian", Character.UnicodeBlock.CYRILLIC),
    Ligurian("Ligurian", Character.UnicodeBlock.BASIC_LATIN),
    Limburgan("Limburgan", Character.UnicodeBlock.BASIC_LATIN),
    Lingala("Lingala", Character.UnicodeBlock.BASIC_LATIN),
    LiteraryChinese("Literary Chinese", Character.UnicodeBlock.CJK_UNIFIED_IDEOGRAPHS),
    Lithuanian("Lithuanian", Character.UnicodeBlock.BASIC_LATIN),
    LivviKarelian("Livvi Karelian", Character.UnicodeBlock.BASIC_LATIN),
    Lojban("Lojban", Character.UnicodeBlock.BASIC_LATIN),
    Lombard("Lombard", Character.UnicodeBlock.BASIC_LATIN),
    LowGerman("Low German", Character.UnicodeBlock.BASIC_LATIN),
    LowerSorbian("Lower Sorbian", Character.UnicodeBlock.BASIC_LATIN),
    Luganda("Luganda", Character.UnicodeBlock.BASIC_LATIN),
    Luxembourgish("Luxembourgish", Character.UnicodeBlock.BASIC_LATIN),
    Macedonian("Macedonian", Character.UnicodeBlock.CYRILLIC),
    Maithili("Maithili", Character.UnicodeBlock.DEVANAGARI),
    Malagasy("Malagasy", Character.UnicodeBlock.BASIC_LATIN),
    Malay("Malay", Character.UnicodeBlock.BASIC_LATIN),
    Malayalam("Malayalam", Character.UnicodeBlock.MALAYALAM),
    Maltese("Maltese", Character.UnicodeBlock.BASIC_LATIN),
    Manx("Manx", Character.UnicodeBlock.BASIC_LATIN),
    Maori("Maori", Character.UnicodeBlock.BASIC_LATIN),
    Marathi("Marathi", Character.UnicodeBlock.DEVANAGARI),
    Mazanderani("Mazanderani", Character.UnicodeBlock.ARABIC),
    MinDong("Min Dong", Character.UnicodeBlock.BASIC_LATIN),
    MinNanChinese("MinNan Chinese", Character.UnicodeBlock.BASIC_LATIN),
    Minangkabau("Minangkabau", Character.UnicodeBlock.BASIC_LATIN),
    Mingrelian("Mingrelian", Character.UnicodeBlock.GEORGIAN),
    Mirandese("Mirandese", Character.UnicodeBlock.BASIC_LATIN),
    ModernGreek("Modern Greek", Character.UnicodeBlock.GREEK),
    Moksha("Moksha", Character.UnicodeBlock.CYRILLIC),
    Mongolian("Mongolian", Character.UnicodeBlock.CYRILLIC, Character.UnicodeBlock.MONGOLIAN),
    Narom("Narom", Character.UnicodeBlock.BASIC_LATIN),
    Navajo("Navajo", Character.UnicodeBlock.BASIC_LATIN),
    Neapolitan("Neapolitan", Character.UnicodeBlock.BASIC_LATIN),
    Nepali("Nepali", Character.UnicodeBlock.DEVANAGARI),
    Newari("Newari", Character.UnicodeBlock.DEVANAGARI),
    NorthernLuri("Northern Luri", Character.UnicodeBlock.ARABIC),
    NorthernSami("Northern Sami", Character.UnicodeBlock.BASIC_LATIN),
    NorthernSotho("Northern Sotho", Character.UnicodeBlock.BASIC_LATIN),
    NorwegianNynorsk("Norwegian Nynorsk", Character.UnicodeBlock.BASIC_LATIN),
    Occitan("Occitan", Character.UnicodeBlock.BASIC_LATIN),
    OldEnglish("OldEnglish", Character.UnicodeBlock.BASIC_LATIN),
    Oriya("Oriya", Character.UnicodeBlock.ORIYA),
    Oromo("Oromo", Character.UnicodeBlock.BASIC_LATIN),
    Ossetian("Ossetian", Character.UnicodeBlock.CYRILLIC),
    PalatineGerman("Palatine German", Character.UnicodeBlock.BASIC_LATIN),
    Pampanga("Pampanga", Character.UnicodeBlock.BASIC_LATIN),
    Pangasinan("Pangasinan", Character.UnicodeBlock.BASIC_LATIN),
    Panjabi("Panjabi", Character.UnicodeBlock.DEVANAGARI),
    Papiamento("Papiamento", Character.UnicodeBlock.BASIC_LATIN),
    PennsylvaniaGerman("Pennsylvania German", Character.UnicodeBlock.BASIC_LATIN),
    Persian("Persian", Character.UnicodeBlock.ARABIC),
    Picard("Picard", Character.UnicodeBlock.BASIC_LATIN),
    Polish("Polish", Character.UnicodeBlock.BASIC_LATIN),
    Portuguese("Portuguese", Character.UnicodeBlock.BASIC_LATIN),
    Pushto("Pushto", Character.UnicodeBlock.ARABIC),
    Quechua("Quechua", Character.UnicodeBlock.BASIC_LATIN),
    Ripuarisch("Ripuarisch", Character.UnicodeBlock.BASIC_LATIN),
    Romanian("Romanian", Character.UnicodeBlock.BASIC_LATIN),
    Romansh("Romansh", Character.UnicodeBlock.BASIC_LATIN),
    Russian("Russian", Character.UnicodeBlock.CYRILLIC),
    Rusyn("Rusyn", Character.UnicodeBlock.CYRILLIC),
    Samogitian("Samogitian", Character.UnicodeBlock.BASIC_LATIN),
    Sanskrit("Sanskrit", Character.UnicodeBlock.DEVANAGARI),
    Sardinian("Sardinian", Character.UnicodeBlock.BASIC_LATIN),
    Saterfriesisch("Saterfriesisch", Character.UnicodeBlock.BASIC_LATIN),
    Scots("Scots", Character.UnicodeBlock.BASIC_LATIN),
    ScottishGaelic("Scottish Gaelic", Character.UnicodeBlock.BASIC_LATIN),
    Serbian("Serbian", Character.UnicodeBlock.CYRILLIC),
    SerboCroatian("Serbo Croatian", Character.UnicodeBlock.BASIC_LATIN),
    Shona("Shona", Character.UnicodeBlock.BASIC_LATIN),
    Sicilian("Sicilian", Character.UnicodeBlock.BASIC_LATIN),
    Silesian("Silesian", Character.UnicodeBlock.BASIC_LATIN),
    Sindhi("Sindhi", Character.UnicodeBlock.ARABIC),
    Sinhala("Sinhala", Character.UnicodeBlock.SINHALA),
    Slovak("Slovak", Character.UnicodeBlock.BASIC_LATIN),
    Slovene("Slovene", Character.UnicodeBlock.BASIC_LATIN),
    Somali("Somali", Character.UnicodeBlock.BASIC_LATIN),
    SouthAzerbaijani("South Azerbaijani", Character.UnicodeBlock.ARABIC),
    Spanish("Spanish", Character.UnicodeBlock.BASIC_LATIN),
    Sranan("Sranan", Character.UnicodeBlock.BASIC_LATIN),
    StandardChinese("Standard Chinese", Character.UnicodeBlock.CJK_UNIFIED_IDEOGRAPHS),
    Sundanese("Sundanese", Character.UnicodeBlock.BASIC_LATIN),
    Swahili("Swahili", Character.UnicodeBlock.BASIC_LATIN),
    Swedish("Swedish", Character.UnicodeBlock.BASIC_LATIN),
    Tagalog("Tagalog", Character.UnicodeBlock.BASIC_LATIN),
    Tajik("Tajik", Character.UnicodeBlock.CYRILLIC),
    Tamil("Tamil", Character.UnicodeBlock.TAMIL),
    Tarantinodialect("Tarantino Dialect", Character.UnicodeBlock.BASIC_LATIN),
    Tatar("Tatar", Character.UnicodeBlock.CYRILLIC),
    Telugu("Telugu", Character.UnicodeBlock.TELUGU),
    Tetum("Tetum", Character.UnicodeBlock.BASIC_LATIN),
    Thai("Thai", Character.UnicodeBlock.THAI),
    Tibetan("Tibetan", Character.UnicodeBlock.TIBETAN),
    Tongan("Tongan", Character.UnicodeBlock.BASIC_LATIN),
    Tswana("Tswana", Character.UnicodeBlock.BASIC_LATIN),
    Tulu("Tulu", Character.UnicodeBlock.KANNADA),
    Turkish("Turkish", Character.UnicodeBlock.BASIC_LATIN),
    Turkmen("Turkmen", Character.UnicodeBlock.BASIC_LATIN),
    Tuvan("Tuvan", Character.UnicodeBlock.CYRILLIC),
    Udmurt("Udmurt", Character.UnicodeBlock.CYRILLIC),
    Uighur("Uighur", Character.UnicodeBlock.ARABIC),
    Ukrainian("Ukrainian", Character.UnicodeBlock.CYRILLIC),
    UpperSorbian("Upper Sorbian", Character.UnicodeBlock.BASIC_LATIN),
    Urdu("Urdu", Character.UnicodeBlock.ARABIC),
    Uzbek("Uzbek", Character.UnicodeBlock.CYRILLIC),
    Venetian("Venetian", Character.UnicodeBlock.BASIC_LATIN),
    Veps("Veps", Character.UnicodeBlock.BASIC_LATIN),
    Vietnamese("Vietnamese", Character.UnicodeBlock.BASIC_LATIN),
    Vlaams("Vlaams", Character.UnicodeBlock.BASIC_LATIN),
    Volapk("Volapk", Character.UnicodeBlock.BASIC_LATIN),
    Vulro("Vulro", Character.UnicodeBlock.BASIC_LATIN),
    Walloon("Walloon", Character.UnicodeBlock.BASIC_LATIN),
    Waray("Waray", Character.UnicodeBlock.BASIC_LATIN),
    Welsh("Welsh", Character.UnicodeBlock.BASIC_LATIN),
    WestLowGerman("West Low German", Character.UnicodeBlock.BASIC_LATIN),
    WesternFrisian("Western Frisian", Character.UnicodeBlock.BASIC_LATIN),
    WesternMari("Western Mari", Character.UnicodeBlock.CYRILLIC),
    WesternPanjabi("Western Panjabi", Character.UnicodeBlock.ARABIC),
    Wolof("Wolof", Character.UnicodeBlock.BASIC_LATIN),
    WuChinese("Wu Chinese", Character.UnicodeBlock.CJK_UNIFIED_IDEOGRAPHS),
    Xhosa("Xhosa", Character.UnicodeBlock.BASIC_LATIN),
    Yakut("Yakut", Character.UnicodeBlock.CYRILLIC),
    Yiddish("Yiddish", Character.UnicodeBlock.HEBREW),
    Yoruba("Yoruba", Character.UnicodeBlock.BASIC_LATIN),
    Zeeuws("Zeeuws", Character.UnicodeBlock.BASIC_LATIN);

    private final CharSequence language;
    private final Character.UnicodeBlock[] scripts;

    Language(CharSequence language, Character.UnicodeBlock... scripts) {
        this.language = language;
        this.scripts = scripts;
    }

    public CharSequence language() {
        return this.language;
    }

    public Character.UnicodeBlock[] scripts() {
        return this.scripts;
    }
}