package ie.gmit.sw;

import static java.lang.Character.*;

/**
 * Enumeration of all 235 languages contained in the Wikipedia Language Identification (WiLi) database.
 * <p>
 * The {@link java.lang.Character.UnicodeScript} of each language is also represented.
 */
public enum Language {
    Achinese("Achinese", UnicodeScript.LATIN),
    Afrikaans("Afrikaans", UnicodeScript.LATIN),
    Albanian("Albanian", UnicodeScript.LATIN),
    AlemannicGerman("Alemannic German", UnicodeScript.LATIN),
    Amharic("Amharic", UnicodeScript.ETHIOPIC),
    Arabic("Arabic", UnicodeScript.ARABIC),
    Aragonese("Aragonese", UnicodeScript.LATIN),
    Armenian("Armenian", UnicodeScript.ARMENIAN),
    Aromanian("Aromanian", UnicodeScript.LATIN),
    Arpitan("Arpitan", UnicodeScript.LATIN),
    Assamese("Assamese", UnicodeScript.BENGALI),
    Asturian("Asturian", UnicodeScript.LATIN),
    Avar("Avar", UnicodeScript.CYRILLIC),
    Aymara("Aymara", UnicodeScript.LATIN),
    Azerbaijani("Azerbaijani", UnicodeScript.LATIN),
    Banjar("Banjar", UnicodeScript.ARABIC),
    Banyumasan("Banyumasan", UnicodeScript.LATIN),
    Bashkir("Bashkir", UnicodeScript.CYRILLIC),
    Basque("Basque", UnicodeScript.LATIN),
    Bavarian("Bavarian", UnicodeScript.LATIN),
    Belarusian("Belarusian", UnicodeScript.CYRILLIC),
    BelarusianTaraschkewiza("Belarusian Taraschkewiza", UnicodeScript.CYRILLIC),
    Bengali("Bengali", UnicodeScript.BENGALI),
    Bhojpuri("Bhojpuri", UnicodeScript.DEVANAGARI),
    Bishnupriya("Bishnupriya", UnicodeScript.BENGALI),
    Bokm("Bokm", UnicodeScript.LATIN),
    Bosnian("Bosnian", UnicodeScript.LATIN),
    Breton("Breton", UnicodeScript.LATIN),
    Bulgarian("Bulgarian", UnicodeScript.CYRILLIC),
    Burmese("Burmese", UnicodeScript.MYANMAR),
    Buryat("Buryat", UnicodeScript.CYRILLIC),
    Cantonese("Cantonese", UnicodeScript.HAN),
    Catalan("Catalan", UnicodeScript.LATIN),
    Cebuano("Cebuano", UnicodeScript.LATIN),
    CentralBikol("Central Bikol", UnicodeScript.LATIN),
    CentralKhmer("Central Khmer", UnicodeScript.KHMER),
    CentralKurdish("Central Kurdish", UnicodeScript.ARABIC),
    Chavacano("Chavacano", UnicodeScript.LATIN),
    Chechen("Chechen", UnicodeScript.CYRILLIC),
    Cherokee("Cherokee", UnicodeScript.CHEROKEE),
    Chuvash("Chuvash", UnicodeScript.CYRILLIC),
    ClassicalNahuatl("Classical Nahuatl", UnicodeScript.LATIN),
    Cornish("Cornish", UnicodeScript.LATIN),
    Corsican("Corsican", UnicodeScript.LATIN),
    CrimeanTatar("Crimean Tatar", UnicodeScript.LATIN),
    Croatian("Croatian", UnicodeScript.LATIN),
    Czech("Czech", UnicodeScript.LATIN),
    Danish("Danish", UnicodeScript.LATIN),
    Dhivehi("Dhivehi", UnicodeScript.THAANA),
    Dimli("Dimli", UnicodeScript.LATIN),
    Doteli("Doteli", UnicodeScript.DEVANAGARI),
    Dutch("Dutch", UnicodeScript.LATIN),
    EasternMari("Eastern Mari", UnicodeScript.CYRILLIC),
    EgyptianArabic("Egyptian Arabic", UnicodeScript.ARABIC),
    Emilian("Emilian", UnicodeScript.LATIN),
    English("English", UnicodeScript.LATIN),
    Erzya("Erzya", UnicodeScript.CYRILLIC),
    Esperanto("Esperanto", UnicodeScript.LATIN),
    Estonian("Estonian", UnicodeScript.LATIN),
    Extremaduran("Extremaduran", UnicodeScript.LATIN),
    Faroese("Faroese", UnicodeScript.LATIN),
    FijiHindi("Fiji Hindi", UnicodeScript.LATIN),
    Finnish("Finnish", UnicodeScript.LATIN),
    French("French", UnicodeScript.LATIN),
    Friulian("Friulian", UnicodeScript.LATIN),
    Gagauz("Gagauz", UnicodeScript.LATIN),
    Galician("Galician", UnicodeScript.LATIN),
    Georgian("Georgian", UnicodeScript.GEORGIAN),
    German("German", UnicodeScript.LATIN),
    Gilaki("Gilaki", UnicodeScript.ARABIC),
    Guarani("Guarani", UnicodeScript.LATIN),
    Gujarati("Gujarati", UnicodeScript.GUJARATI),
    HaitianCreole("Haitian Creole", UnicodeScript.LATIN),
    HakkaChinese("Hakka Chinese", UnicodeScript.HAN),
    Hausa("Hausa", UnicodeScript.LATIN),
    Hebrew("Hebrew", UnicodeScript.HEBREW),
    Hindi("Hindi", UnicodeScript.DEVANAGARI),
    Hungarian("Hungarian", UnicodeScript.LATIN),
    Icelandic("Icelandic", UnicodeScript.LATIN),
    Ido("Ido", UnicodeScript.LATIN),
    Igbo("Igbo", UnicodeScript.LATIN),
    Iloko("Iloko", UnicodeScript.LATIN),
    Indonesian("Indonesian", UnicodeScript.LATIN),
    Interlingua("Interlingua", UnicodeScript.LATIN),
    Interlingue("Interlingue", UnicodeScript.LATIN),
    Irish("Irish", UnicodeScript.LATIN),
    Italian("Italian", UnicodeScript.LATIN),
    JamaicanPatois("Jamaican Patois", UnicodeScript.LATIN),
    Japanese("Japanese", UnicodeScript.HIRAGANA, UnicodeScript.KATAKANA, UnicodeScript.HAN),
    Javanese("Javanese", UnicodeScript.LATIN),
    Kabardian("Kabardian", UnicodeScript.CYRILLIC),
    Kabyle("Kabyle", UnicodeScript.LATIN),
    Kannada("Kannada", UnicodeScript.KANNADA),
    KarachayBalkar("Karachay Balkar", UnicodeScript.CYRILLIC),
    Karakalpak("Karakalpak", UnicodeScript.LATIN),
    Kashubian("Kashubian", UnicodeScript.LATIN),
    Kazakh("Kazakh", UnicodeScript.CYRILLIC),
    Kinyarwanda("Kinyarwanda", UnicodeScript.LATIN),
    Kirghiz("Kirghiz", UnicodeScript.CYRILLIC),
    Komi("Komi", UnicodeScript.CYRILLIC),
    KomiPermyak("Komi Permyak", UnicodeScript.CYRILLIC),
    Konkani("Konkani", UnicodeScript.LATIN, UnicodeScript.DEVANAGARI),
    Korean("Korean", UnicodeScript.HANGUL),
    Kurdish("Kurdish", UnicodeScript.LATIN),
    Ladino("Ladino", UnicodeScript.LATIN),
    Lao("Lao", UnicodeScript.LAO),
    Latgalian("Latgalian", UnicodeScript.LATIN),
    Latin("Latin", UnicodeScript.LATIN),
    Latvian("Latvian", UnicodeScript.LATIN),
    Lezghian("Lezghian", UnicodeScript.CYRILLIC),
    Ligurian("Ligurian", UnicodeScript.LATIN),
    Limburgan("Limburgan", UnicodeScript.LATIN),
    Lingala("Lingala", UnicodeScript.LATIN),
    LiteraryChinese("Literary Chinese", UnicodeScript.HAN),
    Lithuanian("Lithuanian", UnicodeScript.LATIN),
    LivviKarelian("Livvi Karelian", UnicodeScript.LATIN),
    Lojban("Lojban", UnicodeScript.LATIN),
    Lombard("Lombard", UnicodeScript.LATIN),
    LowGerman("Low German", UnicodeScript.LATIN),
    LowerSorbian("Lower Sorbian", UnicodeScript.LATIN),
    Luganda("Luganda", UnicodeScript.LATIN),
    Luxembourgish("Luxembourgish", UnicodeScript.LATIN),
    Macedonian("Macedonian", UnicodeScript.CYRILLIC),
    Maithili("Maithili", UnicodeScript.DEVANAGARI),
    Malagasy("Malagasy", UnicodeScript.LATIN),
    Malay("Malay", UnicodeScript.LATIN),
    Malayalam("Malayalam", UnicodeScript.MALAYALAM),
    Maltese("Maltese", UnicodeScript.LATIN),
    Manx("Manx", UnicodeScript.LATIN),
    Maori("Maori", UnicodeScript.LATIN),
    Marathi("Marathi", UnicodeScript.DEVANAGARI),
    Mazanderani("Mazanderani", UnicodeScript.ARABIC),
    MinDong("Min Dong", UnicodeScript.LATIN),
    MinNanChinese("MinNan Chinese", UnicodeScript.LATIN),
    Minangkabau("Minangkabau", UnicodeScript.LATIN),
    Mingrelian("Mingrelian", UnicodeScript.GEORGIAN),
    Mirandese("Mirandese", UnicodeScript.LATIN),
    ModernGreek("Modern Greek", UnicodeScript.GREEK),
    Moksha("Moksha", UnicodeScript.CYRILLIC),
    Mongolian("Mongolian", UnicodeScript.CYRILLIC, UnicodeScript.MONGOLIAN),
    Narom("Narom", UnicodeScript.LATIN),
    Navajo("Navajo", UnicodeScript.LATIN),
    Neapolitan("Neapolitan", UnicodeScript.LATIN),
    Nepali("Nepali", UnicodeScript.DEVANAGARI),
    Newari("Newari", UnicodeScript.DEVANAGARI),
    NorthernLuri("Northern Luri", UnicodeScript.ARABIC),
    NorthernSami("Northern Sami", UnicodeScript.LATIN),
    NorthernSotho("Northern Sotho", UnicodeScript.LATIN),
    NorwegianNynorsk("Norwegian Nynorsk", UnicodeScript.LATIN),
    Occitan("Occitan", UnicodeScript.LATIN),
    OldEnglish("OldEnglish", UnicodeScript.LATIN),
    Oriya("Oriya", UnicodeScript.ORIYA),
    Oromo("Oromo", UnicodeScript.LATIN),
    Ossetian("Ossetian", UnicodeScript.CYRILLIC),
    PalatineGerman("Palatine German", UnicodeScript.LATIN),
    Pampanga("Pampanga", UnicodeScript.LATIN),
    Pangasinan("Pangasinan", UnicodeScript.LATIN),
    Panjabi("Panjabi", UnicodeScript.DEVANAGARI),
    Papiamento("Papiamento", UnicodeScript.LATIN),
    PennsylvaniaGerman("Pennsylvania German", UnicodeScript.LATIN),
    Persian("Persian", UnicodeScript.ARABIC),
    Picard("Picard", UnicodeScript.LATIN),
    Polish("Polish", UnicodeScript.LATIN),
    Portuguese("Portuguese", UnicodeScript.LATIN),
    Pushto("Pushto", UnicodeScript.ARABIC),
    Quechua("Quechua", UnicodeScript.LATIN),
    Ripuarisch("Ripuarisch", UnicodeScript.LATIN),
    Romanian("Romanian", UnicodeScript.LATIN),
    Romansh("Romansh", UnicodeScript.LATIN),
    Russian("Russian", UnicodeScript.CYRILLIC),
    Rusyn("Rusyn", UnicodeScript.CYRILLIC),
    Samogitian("Samogitian", UnicodeScript.LATIN),
    Sanskrit("Sanskrit", UnicodeScript.DEVANAGARI),
    Sardinian("Sardinian", UnicodeScript.LATIN),
    Saterfriesisch("Saterfriesisch", UnicodeScript.LATIN),
    Scots("Scots", UnicodeScript.LATIN),
    ScottishGaelic("Scottish Gaelic", UnicodeScript.LATIN),
    Serbian("Serbian", UnicodeScript.CYRILLIC),
    SerboCroatian("Serbo Croatian", UnicodeScript.LATIN),
    Shona("Shona", UnicodeScript.LATIN),
    Sicilian("Sicilian", UnicodeScript.LATIN),
    Silesian("Silesian", UnicodeScript.LATIN),
    Sindhi("Sindhi", UnicodeScript.ARABIC),
    Sinhala("Sinhala", UnicodeScript.SINHALA),
    Slovak("Slovak", UnicodeScript.LATIN),
    Slovene("Slovene", UnicodeScript.LATIN),
    Somali("Somali", UnicodeScript.LATIN),
    SouthAzerbaijani("South Azerbaijani", UnicodeScript.ARABIC),
    Spanish("Spanish", UnicodeScript.LATIN),
    Sranan("Sranan", UnicodeScript.LATIN),
    StandardChinese("Standard Chinese", UnicodeScript.HAN),
    Sundanese("Sundanese", UnicodeScript.LATIN),
    Swahili("Swahili", UnicodeScript.LATIN),
    Swedish("Swedish", UnicodeScript.LATIN),
    Tagalog("Tagalog", UnicodeScript.LATIN),
    Tajik("Tajik", UnicodeScript.CYRILLIC),
    Tamil("Tamil", UnicodeScript.TAMIL),
    Tarantinodialect("Tarantino Dialect", UnicodeScript.LATIN),
    Tatar("Tatar", UnicodeScript.CYRILLIC),
    Telugu("Telugu", UnicodeScript.TELUGU),
    Tetum("Tetum", UnicodeScript.LATIN),
    Thai("Thai", UnicodeScript.THAI),
    Tibetan("Tibetan", UnicodeScript.TIBETAN),
    Tongan("Tongan", UnicodeScript.LATIN),
    Tswana("Tswana", UnicodeScript.LATIN),
    Tulu("Tulu", UnicodeScript.KANNADA),
    Turkish("Turkish", UnicodeScript.LATIN),
    Turkmen("Turkmen", UnicodeScript.LATIN),
    Tuvan("Tuvan", UnicodeScript.CYRILLIC),
    Udmurt("Udmurt", UnicodeScript.CYRILLIC),
    Uighur("Uighur", UnicodeScript.ARABIC),
    Ukrainian("Ukrainian", UnicodeScript.CYRILLIC),
    UpperSorbian("Upper Sorbian", UnicodeScript.LATIN),
    Urdu("Urdu", UnicodeScript.ARABIC),
    Uzbek("Uzbek", UnicodeScript.CYRILLIC),
    Venetian("Venetian", UnicodeScript.LATIN),
    Veps("Veps", UnicodeScript.LATIN),
    Vietnamese("Vietnamese", UnicodeScript.LATIN),
    Vlaams("Vlaams", UnicodeScript.LATIN),
    Volapk("Volapk", UnicodeScript.LATIN),
    Vulro("Vulro", UnicodeScript.LATIN),
    Walloon("Walloon", UnicodeScript.LATIN),
    Waray("Waray", UnicodeScript.LATIN),
    Welsh("Welsh", UnicodeScript.LATIN),
    WestLowGerman("West Low German", UnicodeScript.LATIN),
    WesternFrisian("Western Frisian", UnicodeScript.LATIN),
    WesternMari("Western Mari", UnicodeScript.CYRILLIC),
    WesternPanjabi("Western Panjabi", UnicodeScript.ARABIC),
    Wolof("Wolof", UnicodeScript.LATIN),
    WuChinese("Wu Chinese", UnicodeScript.HAN),
    Xhosa("Xhosa", UnicodeScript.LATIN),
    Yakut("Yakut", UnicodeScript.CYRILLIC),
    Yiddish("Yiddish", UnicodeScript.HEBREW),
    Yoruba("Yoruba", UnicodeScript.LATIN),
    Zeeuws("Zeeuws", UnicodeScript.LATIN);

    private final CharSequence language;
    private final UnicodeScript[] scripts;

    Language(CharSequence language, UnicodeScript... scripts) {
        this.language = language;
        this.scripts = scripts;
    }

    public CharSequence language() {
        return this.language;
    }

    public UnicodeScript[] scripts() {
        return this.scripts;
    }
}