package ie.gmit.sw;

/**
 * Enumeration of all 235 languages contained in the Wikipedia Language Identification (WiLi) database.
 *
 * The script of each language is also represented, however it is not fully accurate (for instance, most languages
 * don't use "Basic Latin" but rather an extended character set which includes diacritics and other special characters).
 *
 * @see Script
 */
public enum Language {
    Achinese ("Achinese", Script.Basic_Latin),
    Afrikaans ("Afrikaans", Script.Basic_Latin),
    Albanian ("Albanian", Script.Basic_Latin),
    AlemannicGerman ("Alemannic German", Script.Basic_Latin),
    Amharic ("Amharic", Script.Ethiopic),
    Arabic ("Arabic", Script.Arabic),
    Aragonese ("Aragonese", Script.Basic_Latin),
    Armenian ("Armenian", Script.Armenian),
    Aromanian ("Aromanian", Script.Basic_Latin),
    Arpitan ("Arpitan", Script.Basic_Latin),
    Assamese ("Assamese", Script.Bengali),
    Asturian ("Asturian", Script.Basic_Latin),
    Avar ("Avar", Script.Cyrillic),
    Aymara ("Aymara", Script.Basic_Latin),
    Azerbaijani ("Azerbaijani", Script.Basic_Latin),
    Banjar ("Banjar", Script.Arabic),
    Banyumasan ("Banyumasan", Script.Basic_Latin),
    Bashkir ("Bashkir", Script.Cyrillic),
    Basque ("Basque", Script.Basic_Latin),
    Bavarian ("Bavarian", Script.Basic_Latin),
    Belarusian ("Belarusian", Script.Cyrillic),
    BelarusianTaraschkewiza ("Belarusian Taraschkewiza", Script.Cyrillic),
    Bengali ("Bengali", Script.Bengali),
    Bhojpuri ("Bhojpuri", Script.Devanagari),
    Bishnupriya ("Bishnupriya", Script.Bengali),
    Bokm ("Bokm", Script.Basic_Latin),
    Bosnian ("Bosnian", Script.Basic_Latin),
    Breton ("Breton", Script.Basic_Latin),
    Bulgarian ("Bulgarian", Script.Cyrillic),
    Burmese ("Burmese", Script.Myanmar),
    Buryat ("Buryat", Script.Cyrillic),
    Cantonese ("Cantonese", Script.CJK),
    Catalan ("Catalan", Script.Basic_Latin),
    Cebuano ("Cebuano", Script.Basic_Latin),
    CentralBikol ("Central Bikol", Script.Basic_Latin),
    CentralKhmer ("Central Khmer", Script.Khmer),
    CentralKurdish ("Central Kurdish", Script.Arabic),
    Chavacano ("Chavacano", Script.Basic_Latin),
    Chechen ("Chechen", Script.Cyrillic),
    Cherokee ("Cherokee", Script.Cherokee),
    Chuvash ("Chuvash", Script.Cyrillic),
    ClassicalNahuatl ("Classical Nahuatl", Script.Basic_Latin),
    Cornish ("Cornish", Script.Basic_Latin),
    Corsican ("Corsican", Script.Basic_Latin),
    CrimeanTatar ("Crimean Tatar", Script.Basic_Latin),
    Croatian ("Croatian", Script.Basic_Latin),
    Czech ("Czech", Script.Basic_Latin),
    Danish ("Danish", Script.Basic_Latin),
    Dhivehi ("Dhivehi", Script.Thanna),
    Dimli ("Dimli", Script.Basic_Latin),
    Doteli ("Doteli", Script.Devanagari),
    Dutch ("Dutch", Script.Basic_Latin),
    EasternMari ("Eastern Mari", Script.Cyrillic),
    EgyptianArabic ("Egyptian Arabic", Script.Arabic),
    Emilian ("Emilian", Script.Basic_Latin),
    English ("English", Script.Basic_Latin),
    Erzya ("Erzya", Script.Cyrillic),
    Esperanto ("Esperanto", Script.Basic_Latin),
    Estonian ("Estonian", Script.Basic_Latin),
    Extremaduran ("Extremaduran", Script.Basic_Latin),
    Faroese ("Faroese", Script.Basic_Latin),
    FijiHindi ("Fiji Hindi", Script.Basic_Latin),
    Finnish ("Finnish", Script.Basic_Latin),
    French ("French", Script.Basic_Latin),
    Friulian ("Friulian", Script.Basic_Latin),
    Gagauz ("Gagauz", Script.Basic_Latin),
    Galician ("Galician", Script.Basic_Latin),
    Georgian ("Georgian", Script.Georgian),
    German ("German", Script.Basic_Latin),
    Gilaki ("Gilaki", Script.Arabic),
    Guarani ("Guarani", Script.Basic_Latin),
    Gujarati ("Gujarati", Script.Gujarati),
    HaitianCreole ("Haitian Creole", Script.Basic_Latin),
    HakkaChinese ("Hakka Chinese", Script.CJK),
    Hausa ("Hausa", Script.Basic_Latin),
    Hebrew ("Hebrew", Script.Hebrew),
    Hindi ("Hindi", Script.Devanagari),
    Hungarian ("Hungarian", Script.Basic_Latin),
    Icelandic ("Icelandic", Script.Basic_Latin),
    Ido ("Ido", Script.Basic_Latin),
    Igbo ("Igbo", Script.Basic_Latin),
    Iloko ("Iloko", Script.Basic_Latin),
    Indonesian ("Indonesian", Script.Basic_Latin),
    Interlingua ("Interlingua", Script.Basic_Latin),
    Interlingue ("Interlingue", Script.Basic_Latin),
    Irish ("Irish", Script.Basic_Latin),
    Italian ("Italian", Script.Basic_Latin),
    JamaicanPatois ("Jamaican Patois", Script.Basic_Latin),
    Japanese ("Japanese", Script.Katakana, Script.Hiragana, Script.CJK),
    Javanese ("Javanese", Script.Basic_Latin),
    Kabardian ("Kabardian", Script.Cyrillic),
    Kabyle ("Kabyle", Script.Basic_Latin),
    Kannada ("Kannada", Script.Kannada),
    KarachayBalkar ("Karachay Balkar", Script.Cyrillic),
    Karakalpak ("Karakalpak", Script.Basic_Latin),
    Kashubian ("Kashubian", Script.Basic_Latin),
    Kazakh ("Kazakh", Script.Cyrillic),
    Kinyarwanda ("Kinyarwanda", Script.Basic_Latin),
    Kirghiz ("Kirghiz", Script.Cyrillic),
    Komi ("Komi", Script.Cyrillic),
    KomiPermyak ("Komi Permyak", Script.Cyrillic),
    Konkani ("Konkani", Script.Basic_Latin, Script.Devanagari),
    Korean ("Korean", Script.CJK),
    Kurdish ("Kurdish", Script.Basic_Latin),
    Ladino ("Ladino", Script.Basic_Latin),
    Lao ("Lao", Script.Lao),
    Latgalian ("Latgalian", Script.Basic_Latin),
    Latin ("Latin", Script.Basic_Latin),
    Latvian ("Latvian", Script.Basic_Latin),
    Lezghian ("Lezghian", Script.Cyrillic),
    Ligurian ("Ligurian", Script.Basic_Latin),
    Limburgan ("Limburgan", Script.Basic_Latin),
    Lingala ("Lingala", Script.Basic_Latin),
    LiteraryChinese ("Literary Chinese", Script.CJK),
    Lithuanian ("Lithuanian", Script.Basic_Latin),
    LivviKarelian ("Livvi Karelian", Script.Basic_Latin),
    Lojban ("Lojban", Script.Basic_Latin),
    Lombard ("Lombard", Script.Basic_Latin),
    LowGerman ("Low German", Script.Basic_Latin),
    LowerSorbian ("Lower Sorbian", Script.Basic_Latin),
    Luganda ("Luganda", Script.Basic_Latin),
    Luxembourgish ("Luxembourgish", Script.Basic_Latin),
    Macedonian ("Macedonian", Script.Cyrillic),
    Maithili ("Maithili", Script.Devanagari),
    Malagasy ("Malagasy", Script.Basic_Latin),
    Malay ("Malay", Script.Basic_Latin),
    Malayalam ("Malayalam", Script.Malayalam),
    Maltese ("Maltese", Script.Basic_Latin),
    Manx ("Manx", Script.Basic_Latin),
    Maori ("Maori", Script.Basic_Latin),
    Marathi ("Marathi", Script.Devanagari),
    Mazanderani ("Mazanderani", Script.Arabic),
    MinDong ("Min Dong", Script.Basic_Latin),
    MinNanChinese ("MinNan Chinese", Script.Basic_Latin),
    Minangkabau ("Minangkabau", Script.Basic_Latin),
    Mingrelian ("Mingrelian", Script.Georgian),
    Mirandese ("Mirandese", Script.Basic_Latin),
    ModernGreek ("Modern Greek", Script.Greek_And_Coptic),
    Moksha ("Moksha", Script.Cyrillic),
    Mongolian ("Mongolian", Script.Cyrillic, Script.Mongolian),
    Narom ("Narom", Script.Basic_Latin),
    Navajo ("Navajo", Script.Basic_Latin),
    Neapolitan ("Neapolitan", Script.Basic_Latin),
    Nepali ("Nepali", Script.Devanagari),
    Newari ("Newari", Script.Devanagari),
    NorthernLuri ("Northern Luri", Script.Arabic),
    NorthernSami ("Northern Sami", Script.Basic_Latin),
    NorthernSotho ("Northern Sotho", Script.Basic_Latin),
    NorwegianNynorsk ("Norwegian Nynorsk", Script.Basic_Latin),
    Occitan ("Occitan", Script.Basic_Latin),
    OldEnglish  ("OldEnglish", Script.Basic_Latin),
    Oriya ("Oriya", Script.Oriya),
    Oromo ("Oromo", Script.Basic_Latin),
    Ossetian ("Ossetian", Script.Cyrillic),
    PalatineGerman ("Palatine German", Script.Basic_Latin),
    Pampanga ("Pampanga", Script.Basic_Latin),
    Pangasinan ("Pangasinan", Script.Basic_Latin),
    Panjabi ("Panjabi", Script.Devanagari),
    Papiamento ("Papiamento", Script.Basic_Latin),
    PennsylvaniaGerman ("Pennsylvania German", Script.Basic_Latin),
    Persian ("Persian", Script.Arabic),
    Picard ("Picard", Script.Basic_Latin),
    Polish ("Polish", Script.Basic_Latin),
    Portuguese ("Portuguese", Script.Basic_Latin),
    Pushto ("Pushto", Script.Arabic),
    Quechua ("Quechua", Script.Basic_Latin),
    Ripuarisch ("Ripuarisch", Script.Basic_Latin),
    Romanian ("Romanian", Script.Basic_Latin),
    Romansh ("Romansh", Script.Basic_Latin),
    Russian ("Russian", Script.Cyrillic),
    Rusyn ("Rusyn", Script.Cyrillic),
    Samogitian ("Samogitian", Script.Basic_Latin),
    Sanskrit ("Sanskrit", Script.Devanagari),
    Sardinian ("Sardinian", Script.Basic_Latin),
    Saterfriesisch ("Saterfriesisch", Script.Basic_Latin),
    Scots ("Scots", Script.Basic_Latin),
    ScottishGaelic ("Scottish Gaelic", Script.Basic_Latin),
    Serbian ("Serbian", Script.Cyrillic),
    SerboCroatian ("Serbo Croatian", Script.Basic_Latin),
    Shona ("Shona", Script.Basic_Latin),
    Sicilian ("Sicilian", Script.Basic_Latin),
    Silesian ("Silesian", Script.Basic_Latin),
    Sindhi ("Sindhi", Script.Arabic),
    Sinhala ("Sinhala", Script.Sinhala),
    Slovak ("Slovak", Script.Basic_Latin),
    Slovene ("Slovene", Script.Basic_Latin),
    Somali ("Somali", Script.Basic_Latin),
    SouthAzerbaijani ("South Azerbaijani", Script.Arabic),
    Spanish ("Spanish", Script.Basic_Latin),
    Sranan ("Sranan", Script.Basic_Latin),
    StandardChinese ("Standard Chinese", Script.CJK),
    Sundanese ("Sundanese", Script.Basic_Latin),
    Swahili ("Swahili", Script.Basic_Latin),
    Swedish ("Swedish", Script.Basic_Latin),
    Tagalog ("Tagalog", Script.Basic_Latin),
    Tajik ("Tajik", Script.Cyrillic),
    Tamil ("Tamil", Script.Tamil),
    Tarantinodialect ("Tarantino Dialect", Script.Basic_Latin),
    Tatar ("Tatar", Script.Cyrillic),
    Telugu ("Telugu", Script.Telugu),
    Tetum ("Tetum", Script.Basic_Latin),
    Thai ("Thai", Script.Thai),
    Tibetan ("Tibetan", Script.Tibeten),
    Tongan ("Tongan", Script.Basic_Latin),
    Tswana ("Tswana", Script.Basic_Latin),
    Tulu ("Tulu", Script.Kannada),
    Turkish ("Turkish", Script.Basic_Latin),
    Turkmen ("Turkmen", Script.Basic_Latin),
    Tuvan ("Tuvan", Script.Cyrillic),
    Udmurt ("Udmurt", Script.Cyrillic),
    Uighur ("Uighur", Script.Arabic),
    Ukrainian ("Ukrainian", Script.Cyrillic),
    UpperSorbian ("Upper Sorbian", Script.Basic_Latin),
    Urdu ("Urdu", Script.Arabic),
    Uzbek ("Uzbek", Script.Cyrillic),
    Venetian ("Venetian", Script.Basic_Latin),
    Veps ("Veps", Script.Basic_Latin),
    Vietnamese ("Vietnamese", Script.Basic_Latin),
    Vlaams ("Vlaams", Script.Basic_Latin),
    Volapk ("Volapk", Script.Basic_Latin),
    Vulro ("Vulro", Script.Basic_Latin),
    Walloon ("Walloon", Script.Basic_Latin),
    Waray ("Waray", Script.Basic_Latin),
    Welsh ("Welsh", Script.Basic_Latin),
    WestLowGerman ("West Low German", Script.Basic_Latin),
    WesternFrisian ("Western Frisian", Script.Basic_Latin),
    WesternMari ("Western Mari", Script.Cyrillic),
    WesternPanjabi ("Western Panjabi", Script.Arabic),
    Wolof ("Wolof", Script.Basic_Latin),
    WuChinese ("Wu Chinese", Script.CJK),
    Xhosa ("Xhosa", Script.Basic_Latin),
    Yakut ("Yakut", Script.Cyrillic),
    Yiddish ("Yiddish", Script.Hebrew),
    Yoruba ("Yoruba", Script.Basic_Latin),
    Zeeuws ("Zeeuws", Script.Basic_Latin);

    private final CharSequence language;
    private final Script[] script;

    Language(CharSequence language) {
        this.language = language;
        script = null;
    }

    Language(CharSequence language, Script ... script) {
        this.language = language;
        this.script = script;
    }

    public CharSequence getLanguageName() {
        return this.language;
    }

    public Script[] getScript() {
        return this.script;
    }
}